name: Automatic release
on:
  push:
    branches: ['main']
jobs:
  release:
    name: Run build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: main 
